// Auto-generated by scripts/generate-icon-types.mjs
// Do not edit manually. Run: npm run icons:generate-types

export type GeneratedIconName =
  | "home"
  | "search"
  | "user";

export const AVAILABLE_ICONS: string[] = [
  "home",
  "search",
  "user",
];
